### ISSUE TITLE
Delete smooshed files?

### ISSUE THREAD

**Issue by callumlocke** [gabrielflorit/gulp-smoosher#12]
Could there be an option to delete the external assets after they are smooshed?

Or do you recommend another strategy?

**Comment by gabrielflorit** [comment]
Not sure I follow. In this example https://github.com/gabrielflorit/gulp-smoosher#example, which file do you want deleted?

**Comment by callumlocke** [comment]
`styles.css`, because its contents have been inlined in the HTML, so that file is no longer needed.

**Comment by gabrielflorit** [comment]
Closing - but do let me know if this is still an issue for you.
