### ISSUE TITLE
Uncss inlined css

### ISSUE THREAD

**Issue by goschevski** [gabrielflorit/gulp-smoosher#14]
It would be great if plugin could after inlining css, remove unused css for that html page.

I tried to combine smoosher with gulp-uncss but it seems that's not possible. That's way it would be nice to have option `uncss: true`. :)

**Comment by arthurvr** [comment]
Why don't you just uncss before inlining? This breaks separation of concerns and would overcomplicate. There's gulp-uncss for that.

**Comment by goschevski** [comment]
Because gulp-uncss accept array of html files and then uncss css file using html files for reference. What I want is to uncss every html page separately. I don't want to use classes which are maybe used for some other page.

Example: http://www.keithclark.co.uk/

As you can see, every page has only the css needed for that page.

**Comment by gabrielflorit** [comment]
I'm quite hesitant to implement this, but maybe I don't fully understand your requirement. Could you post a detailed example of your proposed workflow?

**Comment by goschevski** [comment]
This is a task for uncss module and there is an [issue](https://github.com/giakki/uncss/issues/69) for that, but until they resolve it, it would be great if smoosher could uncss asset for current html page after inlining it.

In last comment I pasted url of Keith Clark's site, where you can see that every page have CSS which is necessary only for that specific page. 

With uncss feature added to smoosher, we could achieve the same. At least until guys who are working on uncss resolve [#69](https://github.com/giakki/uncss/issues/69).

**Comment by gabrielflorit** [comment]
Could you loop through your html files, one at a time, and perform whatever gulp operations you want?

**Comment by goschevski** [comment]
Sorry, I don't understand what are you trying to say.

If this is too difficult or you think smoosher shouldn't care about those things, it's totally fine, this is only suggestion. No hard feelings. :)

**Comment by gabrielflorit** [comment]
Let me know if you have any further thoughts on this issue, glad to help. In the meantime I'll close it.
