### ISSUE TITLE
do not delete propertys after smooshing..

### ISSUE THREAD

**Issue by nimo23** [gabrielflorit/gulp-smoosher#16]
Actually this 

`<script type="application/json" id="my-id" src=".."></script>`

becomes this after using smoosher

`<script>
..content
</script>`

But I need my id and I need my type-propery. Please do not delete these propertys after smoosing.

**Comment by gabrielflorit** [comment]
oh, good point.

**Comment by gabrielflorit** [comment]
Might go without saying, but I'm only going to do this for `script`.

**Comment by gabrielflorit** [comment]
Done. Let me know if this works for you.

**Comment by nimo23** [comment]
Yes, fine! It works as expected. Thanks for the fast job!
