### ISSUE TITLE
path resolving

### ISSUE THREAD

**Issue by TxHawks** [gabrielflorit/gulp-smoosher#17]
It would be useful to have a way to transform paths, so that, for instance, if my `css` file was in the `styles` directory, and had a rule of `background-image: url(../images/some-image.png)` it could be transformed into `background-image: url(images/some-image.png)` (sans the `../`) in the inlined css.

Or does this already exist and I'm missing something?

**Comment by gabrielflorit** [comment]
It doesn't exist, no.

**Comment by TxHawks** [comment]
For future reference, I ended up solving using with `gulp-replace`:
`.pipe($.replace('url("../', 'url("'))`

Thanks

**Comment by gabrielflorit** [comment]
Nice.
